version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - cd vite-project
      - npm ci --legacy-peer-deps
  
  build:
    commands:
      - echo Building the React app...
      - npm run build

  # post_build:
  #   commands:
  #     - echo Deploying to S3...
  #     - aws s3 sync vite-project/dist s3://www.connorsgames.com --delete

artifacts:
  files:
    - '**/*'
  base-directory: vite-project/dist
  discard-paths: no