version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - cd vite-project
      - npm ci --legacy-peer-deps
  
  build:
    commands:
      - echo Building the React app...
      - npm run build

  post_build:
    commands:
      - echo Deploying to S3...
      - ls -al
      - aws s3 sync dist s3://your-s3-bucket-name --delete
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id E32R0XQN7T0LPK --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: vite-project/dist
  discard-paths: no