version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - cd vite-project
      - npm ci --legacy-peer-deps
  
  build:
    commands:
      - echo Building the React app...
      - cd vite-project
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: no